version: 2

sources:
  - name: shopify_raw
    database: "{{ 'smb-dataplatform' if target.name == 'prod' else 'shopify_db' }}"
    schema: "{{ 'shopify_data_raw' if target.name == 'prod' else 'shopify_data' }}"
    description: "Raw data from Shopify, stored in the 'shopify_data' dataset in BigQuery."
    tables:
      - name: orders
        description: "Raw orders data from Shopify."

  - name: meta_raw
    database: "{{ 'smb-dataplatform' if target.name == 'prod' else 'facebook_db' }}"
    schema: "{{ 'facebook_ads_data' if target.name == 'prod' else 'main' }}"
    description: "Raw ad spend data from Meta (Facebook), stored in the 'facebook_ads_data' dataset in BigQuery."
    tables:
      - name: ads_insights
        description: "Raw daily ad spend from Meta."

  - name: tiktok_raw
    database: "{{ 'smb-dataplatform' if target.name == 'prod' else 'tiktok_db' }}"
    schema: "{{ 'tiktok_ads_data' if target.name == 'prod' else 'main' }}"
    description: "Raw ad spend data from TikTok, stored in the 'tiktok_ads_data' dataset in BigQuery."
    tables:
      - name: ad_reports
        description: "Raw daily ad spend from TikTok."

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: net_sales
        tests:
          - not_negative
      - name: cogs
        tests:
          - not_negative
  - name: stg_meta_ads
    columns:
      - name: date_day
        tests:
          - not_null
      - name: spend
        tests:
          - not_negative
      - name: publisher_platform
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['facebook', 'instagram']
  - name: stg_tiktok_ads
    columns:
      - name: date_day
        tests:
          - not_null
      - name: spend
        tests:
          - not_negative